"""
SAT-GUARDIAN: Three-Frame Generator
=====================================
Cascaded intermediate frame generation at α = 0.25, 0.50, 0.75.

Generation Order (cascaded)
---------------------------
1. generate_mid_frame()         → T0.50  (between T0 and T1)
2. generate_quarter_frame()     → T0.25  (between T0 and T0.50)
3. generate_three_quarter_frame() → T0.75  (between T0.50 and T1)

Two strategies are supported:
  - "flow"  : pure flow-based bilinear warping (no neural network required)
  - "model" : LightUNet model prediction (requires trained or untrained model)

The model strategy falls back gracefully to flow-based if no model is provided.
"""

import logging
from typing import Optional, Dict, Tuple
import numpy as np
import torch

from optical_flow import compute_optical_flow, warp_frame, flow_to_magnitude_angle
from interpolation_model import LightUNet, frames_to_tensor, get_device

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Low-level: single-alpha frame generation
# ---------------------------------------------------------------------------

def _blend_warped(
    frame_src: np.ndarray,
    frame_dst: np.ndarray,
    flow_fwd:  np.ndarray,
    flow_bwd:  np.ndarray,
    alpha:     float,
) -> np.ndarray:
    """
    Generate intermediate frame at position `alpha` using bilateral warping.

    Frame at alpha is estimated as:
        warped_fwd = warp(src, alpha * flow_fwd)
        warped_bwd = warp(dst, (1-alpha) * flow_bwd)
        blended    = (1-alpha)*warped_fwd + alpha*warped_bwd

    Parameters
    ----------
    frame_src, frame_dst : (H, W) float32 in [0,1]
    flow_fwd : (H,W,2) forward flow from src→dst
    flow_bwd : (H,W,2) backward flow from dst→src
    alpha : float in (0,1) – temporal position
    """
    warped_fwd = warp_frame(frame_src, alpha * flow_fwd)
    warped_bwd = warp_frame(frame_dst, (1.0 - alpha) * flow_bwd)
    blended    = (1.0 - alpha) * warped_fwd + alpha * warped_bwd
    return np.clip(blended, 0, 1).astype(np.float32)


def _model_predict(
    model:      LightUNet,
    frame_src:  np.ndarray,
    frame_dst:  np.ndarray,
    flow:       np.ndarray,
    device:     torch.device,
) -> np.ndarray:
    """Run LightUNet inference and return (H, W) float32 frame."""
    mag, _ = flow_to_magnitude_angle(flow)
    mag_norm = (mag - mag.min()) / (mag.max() + 1e-8)

    inp = frames_to_tensor(frame_src, frame_dst, mag_norm, device)
    model.eval()
    with torch.no_grad():
        out = model(inp)  # (1, 1, H, W)
    return out[0, 0].cpu().numpy().astype(np.float32)


# ---------------------------------------------------------------------------
# Public API: individual frame generators
# ---------------------------------------------------------------------------

def generate_mid_frame(
    frame_t0:  np.ndarray,
    frame_t1:  np.ndarray,
    flow_fwd:  np.ndarray,
    flow_bwd:  np.ndarray,
    model:     Optional[LightUNet] = None,
    device:    Optional[torch.device] = None,
    strategy:  str = "flow",
) -> np.ndarray:
    """
    Generate T0.50 – the midpoint frame between T0 and T1.

    Parameters
    ----------
    frame_t0, frame_t1 : (H, W) normalised satellite frames
    flow_fwd : (H, W, 2) physics-constrained forward flow (T0 → T1)
    flow_bwd : (H, W, 2) physics-constrained backward flow (T1 → T0)
    model    : optional LightUNet for neural prediction
    device   : torch device
    strategy : "flow" | "model"

    Returns
    -------
    np.ndarray  (H, W) float32 in [0, 1]
    """
    logger.info("Generating T0.50 ...")
    if strategy == "model" and model is not None:
        if device is None:
            device = get_device()
        # Blend model output with flow warp for stability
        model_pred = _model_predict(model, frame_t0, frame_t1, flow_fwd, device)
        flow_pred  = _blend_warped(frame_t0, frame_t1, flow_fwd, flow_bwd, 0.5)
        frame_mid  = 0.6 * model_pred + 0.4 * flow_pred
    else:
        frame_mid = _blend_warped(frame_t0, frame_t1, flow_fwd, flow_bwd, 0.5)

    return np.clip(frame_mid, 0, 1).astype(np.float32)


def generate_quarter_frame(
    frame_t0:    np.ndarray,
    frame_mid:   np.ndarray,
    flow_fwd:    np.ndarray,
    flow_bwd:    np.ndarray,
    model:       Optional[LightUNet] = None,
    device:      Optional[torch.device] = None,
    strategy:    str = "flow",
) -> np.ndarray:
    """
    Generate T0.25 using cascaded approach: interpolate between T0 and T0.50.

    Parameters
    ----------
    frame_t0   : T0 frame
    frame_mid  : T0.50 frame (generated by generate_mid_frame)
    flow_fwd   : forward flow T0 → T0.50  (half the full-interval flow)
    flow_bwd   : backward flow T0.50 → T0
    """
    logger.info("Generating T0.25 ...")
    # Use half the flow magnitude for the half-interval
    half_flow_fwd = flow_fwd * 0.5
    half_flow_bwd = flow_bwd * 0.5

    if strategy == "model" and model is not None:
        if device is None:
            device = get_device()
        model_pred = _model_predict(model, frame_t0, frame_mid, half_flow_fwd, device)
        flow_pred  = _blend_warped(frame_t0, frame_mid, half_flow_fwd, half_flow_bwd, 0.5)
        frame_q    = 0.6 * model_pred + 0.4 * flow_pred
    else:
        frame_q = _blend_warped(frame_t0, frame_mid, half_flow_fwd, half_flow_bwd, 0.5)

    return np.clip(frame_q, 0, 1).astype(np.float32)


def generate_three_quarter_frame(
    frame_mid:  np.ndarray,
    frame_t1:   np.ndarray,
    flow_fwd:   np.ndarray,
    flow_bwd:   np.ndarray,
    model:      Optional[LightUNet] = None,
    device:     Optional[torch.device] = None,
    strategy:   str = "flow",
) -> np.ndarray:
    """
    Generate T0.75 using cascaded approach: interpolate between T0.50 and T1.

    Parameters
    ----------
    frame_mid : T0.50 frame (generated by generate_mid_frame)
    frame_t1  : T1 frame
    flow_fwd  : forward flow T0.50 → T1  (half the full-interval flow)
    flow_bwd  : backward flow T1 → T0.50
    """
    logger.info("Generating T0.75 ...")
    half_flow_fwd = flow_fwd * 0.5
    half_flow_bwd = flow_bwd * 0.5

    if strategy == "model" and model is not None:
        if device is None:
            device = get_device()
        model_pred = _model_predict(model, frame_mid, frame_t1, half_flow_fwd, device)
        flow_pred  = _blend_warped(frame_mid, frame_t1, half_flow_fwd, half_flow_bwd, 0.5)
        frame_3q   = 0.6 * model_pred + 0.4 * flow_pred
    else:
        frame_3q = _blend_warped(frame_mid, frame_t1, half_flow_fwd, half_flow_bwd, 0.5)

    return np.clip(frame_3q, 0, 1).astype(np.float32)


# ---------------------------------------------------------------------------
# High-level: generate all three frames at once
# ---------------------------------------------------------------------------

def generate_all_frames(
    frame_t0:        np.ndarray,
    frame_t1:        np.ndarray,
    wind_u:          Optional[np.ndarray] = None,
    wind_v:          Optional[np.ndarray] = None,
    model:           Optional[LightUNet]  = None,
    strategy:        str   = "flow",
    flow_params:     Optional[Dict] = None,
    optical_weight:  float = 0.70,
    physics_weight:  float = 0.30,
) -> Dict[str, object]:
    """
    Full pipeline: compute flow → generate T0.25, T0.50, T0.75 via cascade.

    Parameters
    ----------
    frame_t0, frame_t1 : (H, W) float32 normalised satellite frames
    wind_u, wind_v     : (H, W) ERA5 wind components in m/s (optional)
    model              : pre-loaded LightUNet (optional)
    strategy           : "flow" or "model"
    flow_params        : override Farneback parameters

    Returns
    -------
    dict with keys:
        "frame_025", "frame_050", "frame_075"
        "flow_fwd", "flow_bwd",
        "optical_flow_fwd", "optical_flow_bwd",
        "wind_flow_fwd"
    """
    device = get_device() if model is not None else None

    # Forward flow: T0 → T1
    logger.info("Computing forward flow (T0 -> T1) ...")
    flow_fwd, opt_fwd, wind_fwd = compute_optical_flow(
        frame_t0, frame_t1, wind_u, wind_v,
        optical_weight = optical_weight,
        physics_weight = physics_weight,
        flow_params    = flow_params,
    )

    # Backward flow: T1 → T0
    logger.info("Computing backward flow (T1 -> T0) ...")
    flow_bwd, opt_bwd, _ = compute_optical_flow(
        frame_t1, frame_t0, wind_u, wind_v,
        optical_weight = optical_weight,
        physics_weight = physics_weight,
        flow_params    = flow_params,
    )

    # Cascade: T0.50 first, then T0.25 and T0.75
    frame_050 = generate_mid_frame(
        frame_t0, frame_t1, flow_fwd, flow_bwd, model, device, strategy
    )
    frame_025 = generate_quarter_frame(
        frame_t0, frame_050, flow_fwd, flow_bwd, model, device, strategy
    )
    frame_075 = generate_three_quarter_frame(
        frame_050, frame_t1, flow_fwd, flow_bwd, model, device, strategy
    )

    logger.info("All frames generated: T0.25 | T0.50 | T0.75")

    return {
        "frame_025":          frame_025,
        "frame_050":          frame_050,
        "frame_075":          frame_075,
        "flow_fwd":           flow_fwd,
        "flow_bwd":           flow_bwd,
        "optical_flow_fwd":   opt_fwd,
        "optical_flow_bwd":   opt_bwd,
        "wind_flow_fwd":      wind_fwd,
    }
